import React, { useState } from 'react';
import Head from 'next/head'
import { Grid } from "semantic-ui-react";
import { Image, Text, Textarea, Table, Button, Tooltip, Grid as Gr } from "@nextui-org/react";
import { AiOutlinePlusCircle, AiOutlineCloseCircle, AiFillSave } from "react-icons/ai";
import ModalBasic from '@components/Modal';
import UploadFile from '@components/UploadFile';

const Item = () => {
    const [visible, setVisible] = useState(false);

    function openModal() {
        setVisible(true);
    }
    return (
        <>
            <Head>
                <title>Item - 23</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Grid stackable>
                <Grid.Row>
                    <Grid.Column width={2}>
                        <Button
                            color="success"
                            icon={<AiFillSave />}
                            auto>
                            Guardar
                        </Button>
                    </Grid.Column>
                    <Grid.Column width={2}>
                        <Button
                            color="error"
                            icon={<AiOutlineCloseCircle />}
                            auto>
                            Cancelar
                        </Button>
                    </Grid.Column>
                </Grid.Row>
                <Grid.Row>
                    <Grid.Column width={6}>
                        <Image
                            width={320}
                            height={180}
                            src="https://github.com/nextui-org/nextui/blob/next/apps/docs/public/nextui-banner.jpeg?raw=true"
                            alt="Default Image"
                            objectFit="cover"
                        />
                    </Grid.Column>
                    <Grid.Column width={10}>
                        <Grid >
                            <Grid.Column width={8}>
                                <Grid>
                                    <Grid.Row columns={2}>
                                        <Grid.Column width={5}><Text h3>Item</Text></Grid.Column>
                                        <Grid.Column width={10}><Text>23GTY</Text></Grid.Column>
                                    </Grid.Row>
                                    <Grid.Row columns={2}>
                                        <Grid.Column width={5}><Text h3>Descripción</Text></Grid.Column>
                                        <Grid.Column width={10}>
                                            <Textarea
                                                bordered
                                                color="secondary"
                                                labelPlaceholder="Descripción"
                                            />
                                        </Grid.Column>
                                    </Grid.Row>
                                    <Grid.Row columns={2}>
                                        <Grid.Column width={5}><Text h3>Item class</Text></Grid.Column>
                                        <Grid.Column width={10}>Commisariato</Grid.Column>
                                    </Grid.Row>
                                    <Grid.Row columns={2}>
                                        <Grid.Column width={5}><Text h3>Aproval Status</Text></Grid.Column>
                                        <Grid.Column width={10}>Aproved</Grid.Column>
                                    </Grid.Row>
                                    <Grid.Row columns={2}>
                                        <Grid.Column width={5}><Text h3>Creado por</Text></Grid.Column>
                                        <Grid.Column width={10}>yo@test.com</Grid.Column>
                                    </Grid.Row>
                                </Grid>
                            </Grid.Column>
                            <Grid.Column width={8}>
                                <Grid>
                                    <Grid.Row columns={2}>
                                        <Grid.Column width={5}><Text h3>Item status</Text></Grid.Column>
                                        <Grid.Column width={10}><Text>selector</Text></Grid.Column>
                                    </Grid.Row>
                                    <Grid.Row columns={2}>
                                        <Grid.Column width={5}><Text h3>Clico de vida</Text></Grid.Column>
                                        <Grid.Column width={10}><Text>23GTY</Text></Grid.Column>
                                    </Grid.Row>
                                    <Grid.Row columns={2}>
                                        <Grid.Column width={5}><Text h3>User item type</Text></Grid.Column>
                                        <Grid.Column width={10}><Text>Selector</Text></Grid.Column>
                                    </Grid.Row>
                                    <Grid.Row columns={2}>
                                        <Grid.Column width={5}><Text h3>Pack type</Text></Grid.Column>
                                        <Grid.Column width={10}><Text>Selector</Text></Grid.Column>
                                    </Grid.Row>
                                    <Grid.Row columns={2}>
                                        <Grid.Column width={5}><Text h3>Revision</Text></Grid.Column>
                                        <Grid.Column width={10}><Text>0</Text></Grid.Column>
                                    </Grid.Row>
                                    <Grid.Row columns={2}>
                                        <Grid.Column width={5}><Text h3>Feche creación</Text></Grid.Column>
                                        <Grid.Column width={10}><Text>2023-12-12</Text></Grid.Column>
                                    </Grid.Row>
                                </Grid>
                            </Grid.Column>
                        </Grid>
                    </Grid.Column>
                </Grid.Row>
                <Grid.Row>
                    <Gr.Container>
                        <Gr>
                            <Tooltip content="Agregar Attachment" color="primary" placement="right">
                                <Button auto light onClick={openModal}>
                                    <AiOutlinePlusCircle color="green" size={20} />
                                </Button>
                            </Tooltip>
                        </Gr>
                        <Gr>
                            <Tooltip content="Eliminar Attachment" color="error" placement="right">
                                <Button auto light>
                                    <AiOutlineCloseCircle color="red" size={20} />
                                </Button>
                            </Tooltip>
                        </Gr>
                    </Gr.Container>
                </Grid.Row>
                <Grid.Row>
                    <Grid.Column width={16}>
                        <Table
                            aria-label="Example table with custom cells"
                            css={{
                                height: "auto",
                                minWidth: "100%",
                            }}
                            selectionMode="none"
                        >
                            <Table.Header>
                                <Table.Column
                                >
                                    Titulo
                                </Table.Column>
                                <Table.Column
                                >
                                    Descripcion
                                </Table.Column>
                                <Table.Column
                                >
                                    Categoria
                                </Table.Column>
                                <Table.Column
                                >
                                    Tamaño
                                </Table.Column>

                            </Table.Header>
                            <Table.Body>
                                <Table.Row>
                                    <Table.Cell>line1</Table.Cell>
                                    <Table.Cell>line2</Table.Cell>
                                    <Table.Cell>line3</Table.Cell>
                                    <Table.Cell>line2</Table.Cell>
                                </Table.Row>
                            </Table.Body>
                        </Table>
                    </Grid.Column>
                </Grid.Row>
            </Grid>
            <ModalBasic
                visible={visible}
                closeHandler={setVisible}
                textAcep="Cargar"
                title='Cargar Attachment'
                children={<UploadFile />}
            />
        </>
    )
}

export default Item