export { };

declare global {
    /**
     * Now declare things that go in the global namespace,
     * or augment existing declarations in the global namespace.
     */

    interface iProxy {
        getlovs: function
    }

    interface Busqueda {
        item: string,
        keyword: string,
        description: String
    }

    interface Attachment {
        tp: string,
        category: string,
        fileName: string
        title: string,
        desc: string,
        size: number,
        is: number,
        dm: nummber
    }

    interface Select {
        key: number | string,
        text: string,
        value: string
    }

    interface ClassLov {
        PROP: string,
        TEXT: string,
        CODE: string
    }
    type Selection = Array<Select>

    export interface iItems {
        CREATION_DATE: string
        INVENTORY_ITEM_ID: string
        INVENTORY_ITEM_STATUS_CODE: string
        APPROVAL_STATUS: string
        CREATED_BY: string
        CURRENT_PHASE_CODE: string
        ITEM_NUMBER: string
        DESCRIPTION: string
        PRIMARY_UOM_CODE: string
        ITEM_TYPE: string
        FILE_NAME: string
        DM_VERSION_NUMBER: string
        ORGANIZATION_NAME: string
        REVISION: string
        ORG_ID: string
        DM_REPOSITORY: string
        ITEM_CLASS: string
        LIFE_CYCLE: string
        PACK_TYPE: string
    }

    export interface ItemResponse {
        ItemId: number
        OrganizationId: number
        OrganizationCode: string
        ItemClass: string
        Template: any
        ItemNumber: string
        ItemDescription: string
        ApprovalStatusValue: string
        ItemStatusValue: string
        LifecyclePhaseValue: string
        StyleItemFlag: any
        StyleItemNumberValue: string
        Keyword: any
        IgnoreDuplicateItemFlag: any
        UserItemTypeValue: string
        PackTypeValue: string
        LongDescription: any
        FormattedDescription: any
        PrimaryUOMValue: string
        TransactionConversionValue: string
        DefaultingControlValue: any
        PositiveDeviationFactor: number
        NegativeDeviationFactor: number
        CopyItemAndApplyTemplatesFlag: any
        CopyAssociationsFlag: any
        CopyAttachmentsFlag: any
        CopyCategoriesFlag: any
        CopyFromItemValue: any
        CopyFromRevisionValue: any
        CopyFromVersionValue: any
        CopyOrganizationAssignmentsFlag: any
        LastSubmittedNewItemRequest: any
        ChangeNotice: any
        ChangeOrderLineSequenceNumber: any
        StructureItemTypeValue: string
        CreateConfiguredItem: any
        ConfigModelTypeValue: string
        EffectivityControlValue: string
        BaseItemValue: any
        AutoCreatedConfigurationFlag: boolean
        PickComponentsFlag: boolean
        AssembleToOrderFlag: boolean
        CostingEnabledFlag: boolean
        IncludeInRollUpFlag: boolean
        StandardLotSize: any
        InventoryAssetFlag: boolean
        BuildInWIPFlag: boolean
        WIPSupplyTypeValue: string
        WIPSupplyLocatorValue: any
        WIPSupplySubinventoryValue: any
        OvercompletionToleranceTypeValue: any
        OvercompletionToleranceValue: any
        InventoryCarryPenalty: any
        OperationSlackPenalty: any
        RecipeEnabledFlag: boolean
        ProcessQualityEnabledFlag: boolean
        ProcessCostingEnabledFlag: boolean
        ProcessExecutionEnabledFlag: boolean
        ProcessSupplySubinventoryValue: any
        ProcessSupplyLocatorValue: any
        ProcessYieldSubinventoryValue: any
        ProcessYieldLocatorValue: any
        HazardousMaterialFlag: boolean
        CASNumber: any
        AssetTrackedFlag: boolean
        AssetClassValue: string
        ServiceRequestEnabledValue: any
        DefectTrackingOnFlag: any
        ServiceDurationTypeValue: string
        ServiceDuration: any
        ServiceDurationPeriodValue: any
        ServiceStartTypeValue: string
        ServiceStartDelay: number
        AllowSuspendFlag: boolean
        AllowTerminateFlag: boolean
        RequiresItemAssociationFlag: boolean
        CreateFixedAssetFlag: any
        InstanceClassValue: any
        BillingTypeValue: any
        ServiceBillingEnabledFlag: boolean
        RecoveredPartDispositionValue: any
        InventoryItemFlag: boolean
        StockEnabledFlag: boolean
        MaterialTransactionEnabledFlag: boolean
        ReservableFlag: boolean
        CheckMaterialShortageFlag: boolean
        RevisionQuantityControlFlag: boolean
        BulkPickedFlag: boolean
        LotControlValue: string
        StartingLotPrefix: any
        StartingLotNumber: any
        MaturityDays: any
        HoldDays: any
        LotExpirationControlValue: string
        ShelfLifeDays: number
        RetestInterval: any
        ExpirationActionValue: any
        ExpirationActionInterval: any
        ChildLotEnabledFlag: boolean
        ChildLotFormatValidationFlag: boolean
        CopyLotAttributeFlag: boolean
        ChildLotPrefix: any
        ChildLotStartingNumber: any
        ChildLotParent: any
        LotTranslateEnabledFlag: boolean
        LotSplitEnabledFlag: boolean
        LotDivisibleFlag: boolean
        LotSubstitutionEnabledFlag: any
        LotMergeEnabledFlag: boolean
        GradeControlFlag: boolean
        DefaultGradeValue: any
        SerialGenerationValue: string
        SerialStartingPrefix: any
        SerialStartingNumber: any
        NegativeMeasurementError: any
        PositiveMeasurementError: any
        CycleCountEnabledFlag: boolean
        LotStatusEnabledFlag: boolean
        SerialStatusEnabledFlag: boolean
        DefaultLotStatusValue: any
        DefaultSerialStatusValue: any
        RestrictSubinventoriesFlag: boolean
        RestrictLocatorsFlag: boolean
        StockLocatorControlValue: string
        DimensionUOMValue: any
        UnitWidthQuantity: any
        UnitLengthQuantity: any
        UnitHeightQuantity: any
        WeightUOMValue: any
        UnitWeightQuantity: any
        VolumeUOMValue: any
        UnitVolumeQuantity: any
        ContainerItemFlag: any
        ContainerTypeValue: any
        MaximumLoadWeight: any
        VehicleItemFlag: any
        InternalVolume: any
        MinimumFillPercent: any
        WarehouseEquipmentFlag: boolean
        EventFlag: any
        CollateralFlag: any
        CustomerOrderFlag: boolean
        CustomerOrderEnabledFlag: boolean
        ATPComponentsValue: string
        PickingRuleValue: any
        RMAInspectionRequiredFlag: boolean
        EligibilityRuleFlag: any
        ReturnableFlag: boolean
        ATPValue: string
        FinancingAllowedFlag: any
        SalesProductTypeValue: any
        TransactionEnabledFlag: boolean
        OrderManagementIndivisibleFlag: any
        DefaultSalesOrderSourceTypeValue: string
        ElectronicFormatFlag: any
        ShippableFlag: boolean
        DefaultShippingOrganizationValue: any
        ShipModelCompleteFlag: boolean
        DownloadableFlag: any
        OverShipmentTolerance: any
        UnderShipmentTolerance: any
        OverReturnTolerance: any
        UnderReturnTolerance: any
        InvoiceEnabledFlag: boolean
        AccountingRuleValue: any
        PaymentTermsValue: any
        OutputTaxClassificationCodeValue: any
        InvoicedFlag: boolean
        InvoicingRuleValue: any
        SalesAccountValue: any
        WebStatusValue: string
        BackOrderableFlag: any
        OrderableOnWebFlag: boolean
        MinimumLicenseQuantity: any
        InventoryPlanningMethodValue: string
        PlanningMakeBuyValue: string
        Planner: any
        SubcontractingComponentValue: any
        MinimumMinmaxQuantity: any
        MaximumMinmaxQuantity: any
        MinimumOrderQuantity: any
        MaximumOrderQuantity: any
        OrderCost: any
        SourceOrganizationValue: any
        SourceSubinventoryOrganizationValue: any
        SourceSubinventoryValue: any
        FixedOrderQuantity: any
        FixedDaysSupply: any
        FixedLotSizeMultiplier: any
        ReleaseAuthorizationRequiredValue: string
        AutomaticallyExpireASNFlag: boolean
        ConsignedFlag: boolean
        ReplenishmentMinimumOrder: any
        ReplenishmentMaximumOrder: any
        VMIFixedOrderQuantity: any
        ForecastTypelValue: string
        ForecastHorizon: any
        PlanningMethodValue: string
        RoundingControlTypeFlag: any
        CreateSupplyFlag: boolean
        PlanningTimeFence: string
        DemandTimeFence: any
        ReleaseTimeFence: any
        ShrinkageRate: any
        ForecastControlValue: string
        AcceptableEarlyDays: any
        PlanningTimeDays: number
        DemandTimeDays: any
        ReleaseTimeDays: any
        MRPCalculateATPFlag: any
        RepairLeadtime: any
        RepairYield: any
        PreprocessingDays: any
        PostprocessingDays: number
        ProcessingDays: any
        VariableLeadTime: any
        CumulativeTotalLeadTime: any
        FixedLeadTime: any
        CumulativeManufacturingLeadTime: any
        LeadTimeLotSize: number
        PurchasingFlag: boolean
        UseApprovedSupplierFlag: boolean
        NegotiationRequiredFlag: any
        PurchasingInputTaxClassificationValue: any
        InvoiceCloseTolerancePercentage: any
        HazardClassValue: any
        AssetCategoryValue: any
        PurchasableFlag: boolean
        TaxableFlag: boolean
        BuyerOrganizationValue: any
        DefaultBuyerValue: any
        ReceiptCloseTolerancePercentage: any
        UNNumberValue: any
        ListPrice: any
        PriceTolerancePercentage: any
        MarketPrice: any
        RoundingFactor: any
        MatchApprovalLevelValue: any
        MatchConfigurationOptionValue: any
        ReceiptDateActionValue: any
        DaysEarlyReceiptAllowed: any
        DaysLateReceiptAllowed: any
        AllowSubstituteReceiptsFlag: any
        AllowUnorderedReceiptsFlag: any
        QuantityReceivedToleranceAction: any
        QuantityReceivedTolerancePercentage: any
        ItemExtensibleFlexfieldCategoryCode: string
        CreationDate: string
        LastUpdateDate: string
        BackToBackEnabledFlag: boolean
        ContractManufacturingFlag: boolean
        DaysOfCover: any
        DemandPeriod: any
        SafetyStockPlanningMethodValue: any
        OutsideProcessServiceFlag: any
        AllowMaintenanceAssetFlag: any
        EnableGenealogyTrackingFlag: any
        EngineeredItemFlag: boolean
        ProcurementBusinessUnitName: any
        ForcePurchaseLeadTimeFlag: any
        ReplacementTypeValue: any
        BuyerEmailAddress: any
        AssetTrackedValue: string
        RequestId: number
        CreatedBy: string
        CreationDateTime: string
        LastUpdateDateTime: string
        LastUpdateLogin: string
        LastUpdatedBy: string
        InternallyTransferableFlag: boolean
        TransferOrdersEnabledFlag: boolean
        ReplenishmentMaximumDaysOfSupply: any
        CustomerSelfServiceEnabledFlag: any
        AllowPurchasingDocumentDescriptionUpdateFlag: boolean
        EnableContractCoverage: boolean
        CarryingCostPercentage: any
        ReplenishmentMinimumDaysOfSupply: any
        AllowExpressTransactionsFlag: any
        ReceiptRoutingValue: any
        InvoiceMatchOptionValue: any
        CommsActivationRequiredFlag: any
        RequiresFulfillmentLocationFlag: boolean
        IssueUOMValue: any
        EnforceShipToLocationValue: any
        StandardCoverageValue: any
        ReplenishmentSourceTypeValue: any
        TrackingUOMValue: string
        SecondaryUOMValue: any
        PricingUOMValue: string
        HardPeggingLevelValue: any
        CommonSupplyProjectDemandFlag: any
        EnableIotFlag: any
        ExpenditureTypeValue: any
        PackagingStringValue: any
        CreateSupplyAfterDate: any
        CreateFixedAssetValue: any
        UnderCompletionToleranceTypeValue: any
        UnderCompletionToleranceValue: any
        DefaultRepairTransactionName: any
        links: Link[]
    }

    export interface Link {
        rel: string
        href: string
        name: string
        kind: string
    }

    export interface Attachment {
        LastUpdateDate: string
        LastUpdatedBy: string
        DatatypeCode: string
        FileName: string
        DmFolderPath: any
        DmDocumentId: string
        DmVersionNumber: string
        Url: any
        CategoryName: string
        UserName: string
        Uri: any
        FileUrl: string
        UploadedText: any
        UploadedFileContentType: string
        UploadedFileLength: number
        UploadedFileName: any
        ContentRepositoryFileShared: string
        Title: string
        Description: string
        ErrorStatusCode: any
        ErrorStatusMessage: any
        CreatedBy: string
        CreationDate: string
        ExpirationDate: any
        LastUpdatedByUserName: string
        CreatedByUserName: string
        DownloadInfo: string
        DocumentURL: string
      }
}