import { useState, useEffect } from "react"
import Head from 'next/head';
import Link from 'next/link'
import { Input, Button, Text, Tooltip, Grid as Gr, Loading } from "@nextui-org/react";
import { Grid, Table } from "semantic-ui-react"
import { AiFillFileExcel, AiOutlinePlusCircle, AiOutlineCloseCircle } from "react-icons/ai";
import { FaSistrix } from "react-icons/fa"
import ModalBasic from '@components/Modal';
import CreateItem from "@components/CreateItem";
import { createApi } from "service/rest";
import { exportXlsx } from "utils"
import toast from 'react-hot-toast';

export default function Home() {
  const [visible, setVisible] = useState(false);
  const [dataClassItem, setDataClassItem] = useState<any>([]);
  const [clientApi, setClientApi] = useState<any>(null)
  const [searchData, setSearchData] = useState({
    lang: "US",
    itm: "",
    desc: ""
  });
  const [loadSearch, setLoadSearch] = useState(false);
  const [dataTable, setDataTable] = useState<Array<iItems>>([])


  useEffect(() => {
    let api: any = createApi("/api");
    setClientApi(api)
  }, [])


  useEffect(() => {
    if (clientApi !== null) {
      (async () => {
        let arrTemp: any = [];

        let f: Array<ClassLov> = await clientApi.getlovs('US');
        //console.log(await api.items(null, "AS85022"))
        f.map((x) => {
          return arrTemp.push({
            key: x.PROP,
            text: x.TEXT,
            value: x.CODE
          })
        })
        setDataClassItem(arrTemp)
      })()
    }
  }, [clientApi])


  function handlerChange(e: any) {
    const { name, value } = e.target;
    setSearchData({
      ...searchData,
      [name]: value
    })
  }

  function resetFormSearch() {
    setSearchData({
      ...searchData,
      itm: "",
      desc: ""
    });
    setDataTable([])
  }

  async function searchItems() {
    if (!searchData.itm && !searchData.desc) {
      toast.error("Agrega un parametro de busqueda")
    } else if (loadSearch !== true) {
      setLoadSearch(true);
      let result = await clientApi.items(searchData.lang, searchData.itm, searchData.desc);
      setDataTable(result)
      setLoadSearch(false)
    }
  }

  function exportData() {
    if (!dataTable || dataTable.length === 0) {
      toast.error("No data to export")
    } else {
      exportXlsx(dataTable)
    }
  }
  return (
    <>
      <Head>
        <title>Manage Items</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid stackable>
        <Grid.Row columns={2}>

          <Grid.Column width={11}>

            <Grid>
              <Grid.Row>
                <Grid.Column width={7}>
                  <Input
                    clearable
                    bordered
                    labelPlaceholder="Item"
                    name="itm"
                    value={searchData.itm}
                    defaultValue={searchData.itm}
                    size="lg"
                    fullWidth
                    onChange={handlerChange} />
                </Grid.Column>
                <Grid.Column width={7}>
                  <Input clearable bordered labelPlaceholder="Keyword" size="lg" fullWidth />
                </Grid.Column>
              </Grid.Row>
              <Grid.Row>
                <Grid.Column width={14}>
                  <Input
                    clearable
                    bordered
                    labelPlaceholder="Descripcion"
                    name="desc"
                    value={searchData.desc}
                    defaultValue={searchData.desc}
                    size="lg"
                    fullWidth
                    onChange={handlerChange} />
                </Grid.Column>
              </Grid.Row>
            </Grid>

          </Grid.Column>
          <Grid.Column width={5}>
            <>
              <Grid>
                <Grid.Row>
                  <Grid.Column width={5}>
                    <Button
                      color="success"
                      auto size="lg"
                      icon={loadSearch ? null : <FaSistrix />}
                      onPress={searchItems}
                    >
                      {loadSearch ? <Loading type="points" color="currentColor" size="sm" /> : "Buscar"}

                    </Button>
                  </Grid.Column>
                  <Grid.Column width={5}>
                    <Button
                      color="error"
                      auto
                      size="lg"
                      onPress={resetFormSearch}
                      icon={<AiOutlineCloseCircle />}
                    >
                      Resetear
                    </Button>
                  </Grid.Column>
                </Grid.Row>
              </Grid>
            </>
          </Grid.Column>
        </Grid.Row>

        <Grid.Row>
          <Gr.Container>
            <Gr>
              <Text h6>Acciones:</Text>
            </Gr>
            <Gr>
              <Tooltip content="Exportar a excel" color="success" placement="right">
                <Button auto light onPress={exportData}>
                  <AiFillFileExcel color="green" size={20} />
                </Button>
              </Tooltip>

            </Gr>
            <Gr>
              <Tooltip content="Agregar Item" color="primary" placement="right">
                <Button auto light onPress={() => setVisible(true)}>
                  <AiOutlinePlusCircle color="green" size={20} />
                </Button>
              </Tooltip>
            </Gr>
            <Gr>
              <Tooltip content="Eliminar Item" color="error" placement="right">
                <Button auto light>
                  <AiOutlineCloseCircle color="red" size={20} />
                </Button>
              </Tooltip>
            </Gr>
          </Gr.Container>
        </Grid.Row>


        <Grid.Row>
          <Grid.Column width={16}>
            <Table celled>
              <Table.Header>
                <Table.Row>
                  <Table.HeaderCell>Item</Table.HeaderCell>
                  <Table.HeaderCell>Descripción</Table.HeaderCell>
                  <Table.HeaderCell>Organización</Table.HeaderCell>
                  <Table.HeaderCell>Class</Table.HeaderCell>
                  <Table.HeaderCell>Unidad de medida</Table.HeaderCell>
                </Table.Row>
              </Table.Header>

              <Table.Body>
                {dataTable.map((x) => (
                  <Table.Row key={x.INVENTORY_ITEM_ID}>
                    <Table.Cell>
                      <Link href={`item/${x.ITEM_NUMBER}`}>{x.ITEM_NUMBER}</Link>
                    </Table.Cell>
                    <Table.Cell>{x.DESCRIPTION}</Table.Cell>
                    <Table.Cell>{x.ORGANIZATION_NAME}</Table.Cell>
                    <Table.Cell>None</Table.Cell>
                    <Table.Cell>{x.INVENTORY_ITEM_STATUS_CODE}</Table.Cell>
                  </Table.Row>
                ))}
              </Table.Body>
            </Table>
          </Grid.Column>
        </Grid.Row>
      </Grid>
      <ModalBasic
        visible={visible}
        closeHandler={setVisible}
        textAcep="Crear"
        title='Crear Item'
        children={<CreateItem data={dataClassItem} />}
      />
    </>
  )
}
