SELECT
 ESIB.ITEM_NUMBER
,ESIB.CREATED_BY
,ESIB.CURRENT_PHASE_CODE
,ESIB.CREATION_DATE
,ESIB.INVENTORY_ITEM_STATUS_CODE
,ESIB.APPROVAL_STATUS
,ESIB.INVENTORY_ITEM_ID
,ESIT.DESCRIPTION
,ESIT.LONG_DESCRIPTION
,ORG.ORGANIZATION_CODE organization_name
,EIR.REVISION
,ESIB.PRIMARY_UOM_CODE
,ESIB.ITEM_TYPE
,ESIB.ORGANIZATION_ID AS ORG_ID
,FDT.FILE_NAME
,FDT.DM_VERSION_NUMBER
,FDT.DM_REPOSITORY
FROM
 EGP_SYSTEM_ITEMS_B ESIB,
 EGP_SYSTEM_ITEMS_TL ESIT,
 INV_ORG_PARAMETERS ORG,
 EGP_ITEM_REVISIONS_B EIR,
 FND_ATTACHED_DOCUMENTS FAD,
 FND_DOCUMENTS_TL FDT
WHERE 1=1
AND ESIB.ITEM_NUMBER LIKE '%' || NVL(:P_ITEM, ESIB.ITEM_NUMBER) || '%'
AND ESIB.ORGANIZATION_ID = NVL(:ORG_ID,ESIB.ORGANIZATION_ID)
AND ESIT.INVENTORY_ITEM_ID = ESIB.INVENTORY_ITEM_ID
AND ESIT.ORGANIZATION_ID = ESIB.ORGANIZATION_ID
AND ESIT.DESCRIPTION LIKE '%' || NVL(:P_DESC, ESIT.DESCRIPTION) || '%'
AND ESIT.LANGUAGE = NVL(:LANG,'US')
AND ORG.ORGANIZATION_ID = ESIB.ORGANIZATION_ID
AND EIR.INVENTORY_ITEM_ID = ESIB.INVENTORY_ITEM_ID
AND EIR.ORGANIZATION_ID = ESIB.ORGANIZATION_ID
AND FAD.PK1_VALUE(+) = ESIB.ORGANIZATION_ID
AND FAD.PK2_VALUE(+) = ESIB.INVENTORY_ITEM_ID
AND FAD.PRIMARY_CATEGORY_FLAG(+) = 'Y'
AND FDT.DOCUMENT_ID(+) = FAD.DOCUMENT_ID
AND FDT.LANGUAGE(+) = NVL(:LANG, 'US') 



SELECT 
EIC.ITEM_CLASS_CODE
FROM
EGP_ITEM_CLASSES_B EIC,
EGP_ITEMCLASS_PHASES EICP
WHERE 1=1
AND EICP.PHASE_CODE = 'Production'
AND EIC.PARENT_ITEM_CLASS_ID = EICP.CATEGORY_ID


