SELECT
    EICB.ITEM_CLASS_ID AS PROP,
    EICT.ITEM_CLASS_NAME AS TEXT,
    EICB.ITEM_CLASS_CODE AS CODE
FROM
    EGP_ITEM_CLASSES_B EICB,
    EGP_ITEM_CLASSES_TL EICT
WHERE 1=1
AND EICT.ITEM_CLASS_ID = EICB.ITEM_CLASS_ID
AND EICT.LANGUAGE = NVL(:LANG,'US')


SELECT
 ESIB.ITEM_NUMBER
,ESIB.CREATED_BY
,ESIB.CURRENT_PHASE_CODE
,ESIB.CREATION_DATE
,ESIB.INVENTORY_ITEM_STATUS_CODE
,ESIB.APPROVAL_STATUS
,ESIB.INVENTORY_ITEM_ID
,ESIT.DESCRIPTION
,ESIT.LONG_DESCRIPTION
,HRO.name organization_name
FROM
 EGP_SYSTEM_ITEMS_B ESIB,
 EGP_SYSTEM_ITEMS_TL ESIT,
 HR_ORGANIZATION_UNITS_F_TL HRO
WHERE 1=1
AND ESIB.ITEM_NUMBER LIKE '%' || NVL(:P_ITEM,ESIB.ITEM_NUMBER) || '%'
AND ESIT.INVENTORY_ITEM_ID = ESIB.INVENTORY_ITEM_ID
AND ESIT.DESCRIPTION LIKE '%' || NVL(:P_DESC,ESIT.DESCRIPTION) || '%'
AND HRO.ORGANIZATION_ID = ESIB.ORGANIZATION_ID
AND HRO.LANGUAGE = NVL(:LANG,'US')
AND ESIT.LANGUAGE = NVL(:LANG,'US')
GROUP BY  ESIB.ITEM_NUMBER
,ESIB.CREATED_BY
,ESIB.CURRENT_PHASE_CODE
,ESIB.CREATION_DATE
,ESIB.INVENTORY_ITEM_STATUS_CODE
,ESIB.APPROVAL_STATUS
,ESIB.INVENTORY_ITEM_ID
,ESIT.DESCRIPTION
,ESIT.LONG_DESCRIPTION
,HRO.name

--ORGANIZATION_ID


EGP_ITEM_REVISIONS_B
/fscmService/ItemServiceV2/ItemAttachment?WSDL
/ess/esswebservice?WSDL

https://docs.oracle.com/en/cloud/saas/supply-chain-management/22d/fasrp/op-itemsv2-itemsv2uniqid-child-itemattachment-post.html